language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '5.0'
before_install:
  - npm install -g grunt-cli istanbul
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --require ./node_modules/babel/register.js --require ./node_modules/should/index.js --report lcovonly -- tests/** -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: npm
  email: mguilarducci@gmail.com
  api_key:
    secure: RcGGM2ANclTaD9xsW+jBTjGdpNIx1fI0DxvssIyOlTjcZrYRvvdzGMOrOcx+zJiANwrp7/1zt9giUxF72WaFmu17a6h6ssC/KHLXTgUpIreHkp7/RvhkJY0Ugj2LFwEX1PsnMSqRKseUA0tiqlbxMtCy6LsSfFs4ala7NB/BQZqm1BV6c49MxH42yfsNebqgHRT6QMphO75hfV+mntF7kkam7lxEnRyEUH1+RODgwqY1SE8irLMfvV9syycHoG7zhGuLy/aL/UAC2O66G8fbJMg9otpLSbtV4gqUc6J3TW66f8HJe/pg4nFmTy/lbvuPU8YRmt7ugBMbCcOHm06qbBw7OPiwgqMqkaR5CyYyZowQgnyEHjgSPsiSgakJ8KgzyztjtMIfc1OAztKpgN0TIEf3RDhkODWcf1+k1Rw5qEWH7FqrZc8nXKa4eLlyHBjCWbGzbBA5mDNbgxwmXIERCTx7eHvT4SJUSd4JCwbCQ4bjI14ZNxOL2OQAcXajERpr3pcaRd6usGEnOaNit7Bg6ha0tMAWCw4VQVRQFClT8FcIY69YujrQRgFMN8JW5AWF/s0buMsqaAvCZPt8G2oqydnqsaKEwbKoA8TabaCeN7JvKpGKKjUpUYAGdPFpxIAC9xk1fYdmnu3X9+BAYHpPNlhkkhXGt1Nq2iwYaTRUBdI=
  on:
    tags: true
    repo: stone-pagamentos/node-global-identity
