language: node_js
node_js:
  - '4.0'
  - '4.1'
  - '4.2'
  - '5.0'
  - '5.1'
  - '5.2'
  - '5.3'
before_install:
  - npm install -g grunt-cli istanbul
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --require ./node_modules/babel/register.js --require ./node_modules/should/index.js --report lcovonly -- tests/** -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: npm
  email: mguilarducci@gmail.com
  api_key:
    secure: MMTyS+Ltv4VvAgGM2lCbXXZbHt7JkOzBzWBw2l0KrQDsScm5NzuNXTO9prMiCimJnQ0DdvJPNyOEJVclSlJ9JUaXslYF5IK8y1GX9FNaYSH5kQgR9WgKIe8oWPnqIldnkefTlMOJbjn5/8mpMzxQg0jSJTqm1tuX33Am7AOBfR1q5bBRtqxHEXdUpbX8tEmY6SeZQyD1aRpQVjeVbwYx6MKWxZlkdxCqTxp6xDX+IQ5gTAJHLugESrTUpdN0KymIMtcK76Ezlo0LJFPCqeDosIMJbS8hvoI8S8GRsYW7kV8ayb8DqiPUDPUefU5is/K7Jma+tZor5wTlLTnCNbPGuHkla9O1kUQqPlwEK2k8GmtrYjbDMyUzbEVbOzIEQG4QuM6buwvvVGDpTuWV6mg4jTkJKjy++UdzW92h+PqHUOZlJ1KFwcbmDa88HPwCnZfIg4t0s5F7hNFHA2Y77Uvo3CUws/YthBCktjs+pGkj4Wgc8goNajuCVyrN3HEMhfZuM+ofAnvaN4w+Dh8reOr2M5DJ9+/4AUpB2GcZjTAtHJRkw+e/FVufNg4d02i7Mzx2kzvaI5ZIqoJ8MXrnuCrQJ3g1zihArPVqHkQJ6XUlxl6AyBcfDn1xpL0E8/SRCAqMWsF4leaN198TRAHje015g1Rt6x9T6uHJ+3QBOZlJRAE=
  on:
    tags: true
    repo: stone-pagamentos/node-global-identity
